apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myscript
  name: myscript
spec:
  containers:
  - name: myscript
    image: busybox
    command:
    - sleep
    - "5000"
    volumeMounts:
      - name: log
        mountPath: /var/log

  volumes:
    - name: log
      persistentVolumeClaim:
        claimName: myclaim
